### ISSUE TITLE
can not save if Saved searches was set

### ISSUE THREAD

**Issue by cayhanecamel** [olegbakhirev/due-dates-calendar-widget#2]
An error occurred

detail
java.lang.reflect.InvocationTargetException

**Comment by olegbakhirev** [comment]
Are you using query with several projects? Unfortunately there is an issue in YT if you has an old version of it https://youtrack.jetbrains.com/issue/JT-51310

**Comment by olegbakhirev** [comment]
Please feel free to reopen if it is still the case
