### ISSUE TITLE
error "Can't load information from service"

### ISSUE THREAD

**Issue by DmitriyKhlopin** [olegbakhirev/due-dates-calendar-widget#4]
Добрый день!
Шаги:
1. Выбрать поле с типом 'Date' в настройках виджета.
2. Выбрать проект, в котором используется поле из шага 1.
3. Сохранить виджет.

Результат: ошибка "Can't load information from service"
При этом видно, что отправляется запрос ".../api/issueFolders/0-67/sortOrder/issues?fields=id,idReadable,summary,resolved,fields(id,value(id,name,localizedName,login,avatarUrl,name,presentation,minutes,color(id,foreground,background),isResolved),projectCustomField(id,bundle(id),field(id,name,localizedName,fieldType(id,valueType))))&query= Due Date: 2019-01&$top=50&$skip=0" и на него приходит ответ со списком задач в YouTrack.

Версия виджета - 1.1.0
YouTrack standalone 2018.4.48733

**Comment by olegbakhirev** [comment]
Добрый день, можно уточнить детали, пока не воспроизвести
1. Это происходит при создании виджета в первый раз или при переконфигурировании?
2. Проект выбирается контексте слева или в строке query?
3. Нет ли каких-либо ошибок javascript  в консоли?

Спасибо!

**Comment by DmitriyKhlopin** [comment]
1. В любой ситуации.
2. Слева, на первой из трёх вкладок.
3. Ошибок нет.

При этом, если количество запросов, попадающих под критерии поиска, равно 0, то отображается пустой календарь.

При обновлении выходит 3 запроса:
1. /api/issues?q=%20has:%20{Due%20Date}&$top=1
Не совсем понятно для чего он нужен, т.к. тут нет ограничений по проекту + выводится только 1 issue, даже если их несколько.

2. /api/searchPage?fields=total
В документации ничего не нашёл, но смысл понятен и возвращает правильный результат.

3. /api/issueFolders/0-67/sortOrder/issues?fields=id,idReadable,summary,resolved,fields(id,value(id,name,localizedName,login,avatarUrl,name,presentation,minutes,color(id,foreground,background),isResolved),projectCustomField(id,bundle(id),field(id,name,localizedName,fieldType(id,valueType))))&query=%20Due%20Date%3A%202019-01&$top=50&$skip=0
Тут тоже всегда правильный результат.

Попробовал повторить в своём YouTrack в myjetbrains.com, проблем не возникло...

Если необходимо, то завтра смогу записать видео.

**Comment by olegbakhirev** [comment]
Понятно, спасибо
Запросы все три верные, ошибка может возникать, только если последний из них выдает какую-то ошибку, но Вы говорите статус у него 200.  Наверное, можно было бы записать HAR, если есть такая возможность

**Comment by DmitriyKhlopin** [comment]
2 HAR во вложении. В одном случае запросов в проекте нет, в другом - в проекте 1 запрос.
Из хэдеров удалил authorization.

[yt.zip](https://github.com/olegbakhirev/due-dates-calendar-widget/files/2808073/yt.zip)

**Comment by olegbakhirev** [comment]
Да, в  HAR все окей. Могу предложить сейчас следующее: я сделал сборку виджета для debug, в случае ошибки должен полететь  stack trace. Прикладываю архив, его надо загрузить как кастомный виджет вручную через кнопку New Widget.  Надеюсь увидеть в чем там проблема
[Archive.zip](https://github.com/olegbakhirev/due-dates-calendar-widget/files/2808388/Archive.zip)

**Comment by DmitriyKhlopin** [comment]
Сейчас выходит ошибка после выбора проекта, поля и нажатия на 'Save'.
```
Uncaught (in promise) TypeError: Cannot read property 'isResolved' of null
    at due_dates_calendar_widget.js:379
    at Array.forEach (<anonymous>)
    at due_dates_calendar_widget.js:369
    at Array.forEach (<anonymous>)
    at t.<anonymous> (due_dates_calendar_widget.js:365)
    at r (runtime.js:65)
    at Generator._invoke (runtime.js:303)
    at Generator.e.(/anonymous function) [as next] (https://support.fsight.ru/hub/api/rest/widgets/due-dates-calendar-debug/archive/main.js:46:301162)
    at r (main.js:43695)
    at main.js:43695
```
Оказалось, что у нескольких задач не было указано состояние и тут выходила ошибка:
```
if (field.projectCustomField.field.name === 'State') {
              isResolved = Boolean(field.value.isResolved);
            }
```
Может быть стоит добавить проверку и выводить уведомление?
Можно считать вопрос решенным, спасибо за помощь :)

**Comment by olegbakhirev** [comment]
Отлично, спасибо за содействие, я это внесу в следующую версию. Как раз и хотел посмотреть с какими полями там дело в обработке результата.

**Comment by olegbakhirev** [comment]
Пока добавил проверку состояния этого поля. Если оно отсутствует, задача будет считаться Unresolved
