### ISSUE TITLE
Избыточный вертикальный скроллбар

### ISSUE THREAD

**Issue by DmitriyKhlopin** [olegbakhirev/due-dates-calendar-widget#6]
При любом разрешении (пробовал full hd и 4к) и режиме отображения (день, неделя, месяц) отображается вертикальный скроллбар.
Возможно ли убрать его?
![scrollbar](https://user-images.githubusercontent.com/25894736/51923887-bae11a00-240d-11e9-9695-e1da96058981.png)

**Comment by olegbakhirev** [comment]
Исправил и обновил версию виджета в репозитории виджетов
